package comtest.rsantrod.model.client;

import java.math.BigDecimal;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 02 10:37:17 CEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TestVORowClient extends RowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TestVORowClient() {
    }

    public BigDecimal getViewAttr() {
        return (BigDecimal)getAttribute("ViewAttr");
    }

    public void setViewAttr(BigDecimal value) {
        setAttribute("ViewAttr", value);
    }

    public String getViewAttr1() {
        return (String)getAttribute("ViewAttr1");
    }

    public void setViewAttr1(String value) {
        setAttribute("ViewAttr1", value);
    }

    public String getViewAttr2() {
        return (String)getAttribute("ViewAttr2");
    }

    public void setViewAttr2(String value) {
        setAttribute("ViewAttr2", value);
    }

    public String getViewAttr3() {
        return (String)getAttribute("ViewAttr3");
    }

    public void setViewAttr3(String value) {
        setAttribute("ViewAttr3", value);
    }
}
