package com.avanttic.testfielddefaultvalue.model.bc.views.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 12 13:02:06 CEST 2015
// ---------------------------------------------------------------------
public interface EmployeesViewRow extends Row {
    void emailDefaultValue();
}

