package comtest.rsantrod.model.common;

import java.math.BigDecimal;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 02 10:37:17 CEST 2016
// ---------------------------------------------------------------------
public interface TestVORow extends Row {
    BigDecimal getViewAttr();

    void setViewAttr(BigDecimal value);

    String getViewAttr1();

    void setViewAttr1(String value);

    String getViewAttr2();

    void setViewAttr2(String value);

    String getViewAttr3();

    void setViewAttr3(String value);
}
